version: '3.8'
services:
  ollama:
    build: .
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - llm-network
    restart: unless-stopped

  pgvector:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: <<your password>>
      POSTGRES_DB: vectord_db
    ports:
      - "15432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - llm-network
    restart: unless-stopped

  qdrant:
    image: 'qdrant/qdrant:latest'
    ports:
      - '6333:6333'
      - '6334:6334'
    volumes:
      - qdrant_storage:/qdrant/storage:z
    networks:
      - llm-network
    restart: unless-stopped

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<<your password>>
      - POSTGRES_DB=n8n_db
      - POSTGRES_NON_ROOT_USER=n8n_user
      - POSTGRES_NON_ROOT_PASSWORD=<<your password>>
    ports:
      - "25432:5432"
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - llm-network

  flowwise:
    image: flowiseai/flowise:latest
    ports:
      - "3000:3000"
    environment:
      - FLOWWISE_USERNAME=admin@flowwise.ai
      - FLOWWISE_PASSWORD=<<your password>>
      - OLLAMA_HOST=http://ollama:11434
      - DATABASE_TYPE=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_NAME=flowise
      - DATABASE_USER=flowise
      - DATABASE_PASSWORD=<<your password>>
    volumes:
      - flowwise_data:/app/data
      - /Users/pjaiswal/Documents:/app/public/uploads
    networks:
      - llm-network
    depends_on:
      - ollama
      - pgvector
      - postgres
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=<<your password>>
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
    networks:
      - llm-network
    depends_on:
      - postgres

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - "9000:9000" # Web UI
      - "2500:2500" # SMTP
      - "1100:1100" # POP3
    volumes:
      - inbucket_data:/data
    networks:
      - llm-network
    restart: unless-stopped

volumes:
  ollama_data:
  flowwise_data:
  pgvector_data:
  db_storage:
  n8n_storage:
  qdrant_storage:
  inbucket_data:

networks:
  llm-network:
    driver: bridge
