#!/bin/bash
set -e

POSTGRES_USER=postgres
POSTGRES_PASSWORD=password
N8N_DB=n8n
N8N_USER=n8n
POSTGRES_NON_ROOT_PASSWORD=postgres

FLOWISE_DB=flowise
FLOWISE_USER=flowise

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<EOSQL
  CREATE USER "$N8N_USER" WITH PASSWORD '$POSTGRES_NON_ROOT_PASSWORD';
  CREATE DATABASE "$N8N_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$N8N_DB" TO "$N8N_USER";

  CREATE USER "$FLOWISE_USER" WITH PASSWORD '$POSTGRES_NON_ROOT_PASSWORD';
  CREATE DATABASE "$FLOWISE_DB";
  GRANT ALL PRIVILEGES ON DATABASE "$FLOWISE_DB" TO "$FLOWISE_USER";
EOSQL

PGPASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d "$N8N_DB" -c "ALTER SCHEMA public OWNER TO \"$POSTGRES_USER\";"
PGPASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d "$N8N_DB" -c "GRANT USAGE, CREATE ON SCHEMA public TO \"$N8N_USER\";"

PGPASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d "$FLOWISE_DB" -c "ALTER SCHEMA public OWNER TO \"$POSTGRES_USER\";"
PGPASSWORD="$POSTGRES_PASSWORD" psql -U "$POSTGRES_USER" -d "$FLOWISE_DB" -c "GRANT USAGE, CREATE ON SCHEMA public TO \"$FLOWISE_USER\";"